### PR TITLE
Allow dragging of minimap position.

### PR DESCRIPTION
**Pull request by PrettyFlower**

### CODE REVIEW

**Comment by crudelios** [comment]
I don't think this will work close to the map edge, that's the reason it hasn't been done yet.

**Comment by PrettyFlower** [comment]
Yeah I noticed it gets better pretty janky around the edges. Any thoughts on what it should do around there?

**Comment by crudelios** [comment]
No idea,

I looked at this I think three years ago already, back before augustus even existed, and haven't found a way to do this properly...

**Comment by crudelios** [comment]
Did you change this?

**Comment by PrettyFlower** [comment]
Nope. I was clearing out old branches and accidentally deleted this one. Realized it hadn’t been merged yet so I restored it. Nothing to see here yet tho, still haven’t figured out what to do with the edge scrolling issue.

**Comment by crudelios** [comment]
I think we should close this, you've also hit a brick wall here.

**Pull request closed without merging**
