### PR TITLE
Update french.c

### PR DESCRIPTION
**Pull request by Urides**
Hi,
This is my first pull request on Augustus. I hope I did it correctly this time.

About the changes :

Mainly fixed typos,
improved a few translations,
fixed indentation of the last strings added.

### CODE REVIEW

**Comment by dvincent56** [comment]
Looks good.
Just a doubt about "coût" vs "cout". 
The proposal is correct and come from the new spelling reform in france. (2016). 
We are no longer used to reading it with the ^ character on u.

**Comment by crudelios** [comment]
The only think I don't like are the spaces between text and colons/exclamation marks/question marks.  Is there a specific reason (grammar wise) for that space?

**Comment by dvincent56** [comment]
Yes it's typography rules. there are space between number and %.
But there are no space before question marks or small one so wecan add it
Rules :
http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=2039

**Comment by Urides** [comment]
Thank you for your feedback.

Yes, like dvincent56 said, the spaces are typographical rules. It should even be non-breakable spaces but i'm not sure that type of character is possible here.

**Comment by crudelios** [comment]
All right, thank you, I'll merge then 👍

**Pull request merged**
