### PR TITLE
Draw the ranges of existing wells and fountains when going to place a new one.

### PR DESCRIPTION
**Pull request by PrettyFlower**
I'd like to apologize to @crudelios for this one in advance.

### CODE REVIEW

**Comment by crudelios** [comment]
While I like the idea, I don't like the approach.

Messing with the renderer for this is overkill. 
Also, you're checking tile ranges for each and every water structure, regardless of whether they appear on the map or not.

A much simpler and less intrusive way of doing this would be to check, in `city_without_overlay.c`, which building type was being built and, if it's a water structure, add the blue filter to all tiles that have fountain/well access (you can use `map_terrain_is(grid_offset, TERRAIN_FOUNTAIN_RANGE)` for that.  Grated you'll lose the different color for wells and fountains, but I don't think that's a really important feature.

**Comment by PrettyFlower** [comment]
So I actually tried using the same approach as the water overlay the first time I implemented this, but it didn't work out so great. `TERRAIN_FOUNTAIN_RANGE ` only shows the range of fountains and only when they're on. This means it doesn't work for wells at all (you can see this in the water overlay, only the structures they give access to show up, not the terrain) and it's incredibly annoying for early cities as your fountains are constantly flickering on and off while you wait for workers to arrive.

Now we could fix this by adding a few new terrain options for well water access and fountain water access regardless as to whether the fountain is on, but there's another issue that occurred to me. When you're zoomed out, you actually end up iterating over fewer tiles by going through all the wells and fountains in the city rather than all the visible tiles. The only problem then is I didn't like how fountains with overlapping coverage appeared darker.

That could be worked around by keeping track of which tiles we have already rendered and then adding a check for each one, but I decided it'd be easier to just render it to a separate texture as completely opaque and then render that texture with the opacity I wanted.

**Comment by crudelios** [comment]
You're right, I thought wells also showed, but it's a different mechanic.

I think you can do something like this then in `city_without_overlay.c`, when a water building is being constructed:

```
static void has_building_in_radius(int x, int y, int radius, building_type type) {
    int x_min, y_min, x_max, y_max;
    map_grid_get_area(x, y, size, radius, &x_min, &y_min, &x_max, &y_max);
    for (int yy = y_min; yy <= y_max; yy++) {
        for (int xx = x_min; xx <= x_max; xx++) {
            int building_id = map_building_at(map_grid_offset(xx, yy));
            if (!building_id) {
                continue;
            }
            building *b = building_get(building_id);
            if (b->type == type && b->state == BUILDING_STATE_IN_USE) {
                return 1;
            }
        }
    }
    return 0;
}
```

Then, for each tile to draw, you can do something like:

```
if (has_building_in_radius(x, y, well_range, BUILDING_WELL) || has_building_in_radius(x, y, fountain_range, BUILDING_FOUNTAIN)) {
    // paint me...
}
```

The loops aren't too efficient but this won't really affect performance either.

**Comment by PrettyFlower** [comment]
If I’m understanding correctly, I think that’s going to be really inefficient to the point it would affect performance. Let me know if my math adds up here:

the worst case for the above would be a massive city with no wells or fountains zoomed all the way to out. So like if a player zoomed all the way out at the start of a scenario. The max tiles for a map I think is 162, so we’re looking at ‘162 * 162 * 9 * 9 = 2,125,764’ iterations with the above. 

The worst case scenario for the current approach is a big city with lots of wells and fountains. Assuming something ridiculous like 100 fountains, we’re looking at ’100 * 9 * 9 = 8,100’ iterations.

We could probably add a quick bounds check to the current approach to see if the fountain and its covered area are in camera range.

**Comment by crudelios** [comment]
I'm not entirely sure about the numbers (I think it's even higher), but that's the absolute worst case, while having a fountain/water structure construction active at max zoom out (that's the only case where the range should be drawn). But yeah, it has a ton of duplicated tile checking and would run every frame, which is terribly inefficient and it could slow things down on some computers.

Still, I believe adding special-purpose drawing code to the renderer is no proper solution. This should be handled in the city drawing code and not in the renderer.

There is an alternative which is faster, which is to create a specific "has water access" array with the grid size that is only updated when the user selects a fountain/well button. That way the city drawing code only has to check if the array on that tile is 0 or 1. How to properly implement this to avoid spaghetti code is another question.

**Comment by PrettyFlower** [comment]
I tried to keep the renderer code fairly  generic so it could be reused in other places we might want a separate render buffer (for example, we could do something similar to render walkers behind buildings) but it sounds like you’re not a fan so let’s move on 🙂

I think the water access array you proposed will work just as well and really won’t end up looking too bad. I’ll try it out tonight.

**Comment by crudelios** [comment]
I understand but creating a secondary render target is not the way to go. Hardware rendering is a tricky business and adding a secondary target would likely create all sorts of unexpected issues in many platforms we support.

I'm not fully against messing with the hardware renderer, but only when there is absolutely no alternative.

For example, I'll probably add a function to the renderer to be able to draw any texture's non transparent pixels as a single solid colour. This will allow things like highlighting buildings with any colour we want, finally fixing the ugly sentiment overlay.

**Comment by PrettyFlower** [comment]
Ok after all that this new approach with the has_water_access array is actually slightly faster when zoomed out on a large city.

**Comment by crudelios** [comment]
Ahaha the commit name! But believe me, I don't know if you tested with a display scale other than 100% (not sure it was working), and I'm willing to bet Vita and Switch would freak out with that rendering change.

**Comment by PrettyFlower** [comment]
I’ve got to have some fun with it 😛 I have a widescreen monitor, so I actually always run at 150% display scale. I’ll have to see if I can figure out how to run on switch. Also it occurred to me late last night that I’m not updating the array as new fountains are built, so may want to hold off on this one for a minute.

**Comment by crudelios** [comment]
I'm thinking about this.

I'm not sure that conceptually the range for the existing water structures should be drawn on `city_building_ghost`, but rather on `city_without_overlay`. The building ghost should draw just that... the building ghost (and the new range for the current foutain/well/reservoir ghost).

Also, conceptually, the inner workings of the game (like `building/construction.c`) should not push changes to the UI code (in this case `city_building_ghost.c`). Rather, the UI code should pull the information from the internal city state code and draw the game according to that.

While your code certainly works, on a larger scale, it's easier to follow the overall structure of the game's code if there is only one "flow", that being the user input changes the game's internal behaviour, which the UI fetches its data from.

This may sound picky, but it's one of the reasons why Julius/Augustus' code is relatively easy to understand, despite its lack of comments.

**Comment by PrettyFlower** [comment]
Personally I think it makes more sense to think of the existing water ranges as ghosts themselves and it’s better to keep all that logic in one place, but I can move it to city_without_overlay if you want.

I definitely agree with you that keeping ui code and game code separate is a good thing. In the past I’ve solved the communication issue by having a game update object that each tick of the game loop passes out which the ui can query for event notifications. However I wouldn’t really consider construction.c to be game code since it’s dealing entirely with user input for clicking and dragging structures. It isn’t really part of the core simulation as far as I can tell. Anyways, let me know what you’d like to see here and I can change it around tonight.

**Comment by crudelios** [comment]
I'm actually unsure how it would be best - I'm even thinking a separate file would be best, as this is not really a ghost but not an overlay either.

Regarding the call to `city_building_ghost_set_type`, you don't actually need it at all.

`city_building_ghost_draw` is already called every frame with the current construction type as a parameter (even when there is no construction active) and the last used type is stored on a static variable, so you can compare that static variable with the parameter and if it's different you populate the array, except if the type is `BUILDING_NONE`.

**Comment by PrettyFlower** [comment]
Alright, I think I'm done after this commit. I've spent enough time bikeshedding this feature.

**Pull request merged**
