### PR TITLE
Adding new tooltips for roadblocks and fixing strings

### PR DESCRIPTION
**Pull request by webfischi**
Last request got pulled a bit too fast... please wait until WIP is removed or major update is released

### CODE REVIEW

**Comment by Legionary2** [comment]
Are you on the Augusts discord ? https://discord.com/channels/136544899339124736/282255546977878017

**Comment by crudelios** [comment]
Is this ready to merge @webfischi or do you still have a few more strings to finish?

While you're at it, I recently added more strings at 8b72d5faca68043d232ee9057fae80434e497f4f. Could you please have a look?

**Comment by webfischi** [comment]
I'm sure there are still a few strings that need to be fixed, but i currently don't have the time to do so, but I will add the strings

**Comment by crudelios** [comment]
The expression `Keine Beschränkung` is too large to fit:

city 2021-01-21 16 36 49

Can you make it smaller, please?

Thanks!

**Comment by webfischi** [comment]
Thanks for checking it out

**Comment by webfischi** [comment]
I also noticed that this text is not centered correctly

Inked20201229234516_1_LI

**Comment by crudelios** [comment]
> I also noticed that this text is not centered correctly, the upkeep is also shifted

I think both of them are related to wrong position values, not to the text itself

**Pull request merged**
