### PR TITLE
Feature/buildings rotation

### PR DESCRIPTION
**Pull request by vittoriom94**
Following #38 i thought it would be a good idea to allow the rotation of the hippodrome and the warehouse. I implemented some basic rotation functions (and its hotkey on R).

Note that the hippodrome still requires the first part of the building to be placed near the roads, otherwise the chariot maker will not be able to reach it (I was not sure if this was desired behavior or a bug).

The warehouse rotation might be useful in some particular situations, considering that the base tile is walkable.

To save the rotation, i used the building's subtype.orientation variable. This means that the hippodrome should be replaced in existing saves, because that variable is used to save and retrieve which part of the hippodrome is placed/analyzed.

hippo1
hippo2
warehouse

### CODE REVIEW

**Comment by crudelios** [comment]
Suggestion: allow the `R` key to also rotate the gatehouses, it should be simple enough to adapt as gatehouses already rotate.

**Comment by vittoriom94** [comment]
> Suggestion: allow the `R` key to also rotate the gatehouses, it should be simple enough to adapt as gatehouses already rotate.

Yes, calling `building_construction_update_road_orientation()` when the hotkey is pressed and removing the check on the elapsed time should be enough. This would replace the default rotating behavior, but I think that having both would be overkill and give palyers a headache with the spinning.

**Comment by crudelios** [comment]
I agree the timer should be replaced, but maybe as a config option? So either thebtimer or pressing `R` rotates the gatehouse.

**Comment by Keriew** [comment]
This is great, thank you! But would it not be possible to make it backwards compatible? We know what C3 Hippodrome states are. Even if you are reassigning the state values, could you check if they are the old ones on loading, and if they are, convert them to the new values?

**Comment by vittoriom94** [comment]
> I agree the timer should be replaced, but maybe as a config option? So either thebtimer or pressing `R` rotates the gatehouse.

That would be cool, should I implement it in this PR or maybe a separate one?

> This is great, thank you! But would it not be possible to make it backwards compatible? We know what C3 Hippodrome states are. Even if you are reassigning the state values, could you check if they are the old ones on loading, and if they are, convert them to the new values?

That should be doable! Will work on it in the next days

**Comment by arkimedes1967** [comment]
> Following #38 i thought it would be a good idea to allow the rotation of the hippodrome and the warehouse. I implemented some basic rotation functions (and its hotkey on R).
> 
> Note that the hippodrome still requires the first part of the building to be placed near the roads, otherwise the chariot maker will not be able to reach it (I was not sure if this was desired behavior or a bug).

Sorry for interving, but i think this is relevant for your work in progress:

- I edited the #38 and added another building - **forts**, that i think it should be included in the rotation function. They too are large buildings and aren't squar shaped.
- If you'll include the gatehouse (hotkey R) you might consider also the Triunph Arch for the same reason;
- If you read carefully the #31 and #32 threads, they are related to the rotation option of the buildings. If you could assign the **active face** of a building you might solve both problems: the roadbloks inteceptions problem and the buildings default north for walkers.

Market Left  Market Right

**Comment by crudelios** [comment]
@arkimedes1967 I agree with the first two points you make, but not with the last one. Rotating the spawn point of all square buildings will, in my opinion, add an extra layer of complexity and confusion to the user. Not to mention that while it's relatively simple to mirror a building horizontally, it's not trivial to do so vertically due to the way the game renders graphics.

**Comment by arkimedes1967** [comment]
Even though forts aren't included on the rotation option, hippodrome and warehouses are a great implementation, thank you. I'm looking forward to play the next release with these new features!

**Comment by vittoriom94** [comment]
> Even though forts aren't included on the rotation option, hippodrome and warehouses are a great implementation, thank you. I'm looking forward to play the next release with these new features!

Hopefully I can complete the forts  by this weekend, it's gonna take a little bit more because they're asymmetrical instead of 3 5x5 structures like the hippodrome

**Comment by arkimedes1967** [comment]
> Hopefully I can complete the forts by this weekend, it's gonna take a little bit more because they're asymmetrical instead of 3 5x5 structures like the hippodrome

You're Awesome, @vittoriom94 . Thank you!

**Comment by vittoriom94** [comment]
This is the result with forts rotation of the last commit:
city 2020-06-27 12 06 26

From a different city orientation:
city 2020-06-27 12 06 29

**Comment by arkimedes1967** [comment]
@Keriew  will it be available on the next unstable release, please?

**Comment by Keriew** [comment]
Looks amazing!

One comment about the style, though: In Julius all nonstatic functions have a prefix in their name indicating their folder, and name of source file they are in. So all the functions in building/industry.c start with building_industry_[function name]. Coudl you rename the new functions to that standard?

**Comment by vittoriom94** [comment]
> One comment about the style, though: In Julius all nonstatic functions have a prefix in their name indicating their folder, and name of source file they are in. So all the functions in building/industry.c start with building_industry_[function name]. Coudl you rename the new functions to that standard?

Done! Shouldn't have forgotten anything

**Comment by Keriew** [comment]
It's a great addition! Thank you!

**Pull request merged**
