### PR TITLE
Fix Vita compilation

### PR DESCRIPTION
**Pull request by devnoname120**
It still crashes, but at least now it compiles and installs properly.

### CODE REVIEW

**Comment by crudelios** [comment]
Thanks for this. I'm waiting for the latest Julius merges to Augustus, which make integrating the Vita/Switch code easier.

Ideally the joystick-support branch from Julius could also be added, but that one is not nearly as important.

**Comment by crudelios** [comment]
This is now outdated due to the latest merges from base Julius.

Thanks for your help @devnoname120. I'm closing this PR and later I'll use what I can from it when I get around to adding Vita support for assets :+1:

**Comment by devnoname120** [comment]
@crudelios I've also updated the PS Vita live area assets in this PR. Make sure to pick up the changes :)

**Comment by crudelios** [comment]
Thanks, I will!

I want to get proper mod support going, to keep performance good enough I'll probably need to create my own docker image with a custom build of SDL-Vita using [this PR's code](https://github.com/isage/SDL-mirror/pull/1).

A little ways to go still!

**Pull request closed without merging**
