### PR TITLE
Resource stockpiling

### PR DESCRIPTION
**Pull request by ipanic**
This pull request adds two new options:
1. Ability to stockpile raw resources/farm products/fish directly to warehouse instead of workshop/granary. Like global city feature, but only per building. Option disabled by default

2. Ability to disable warehouse cartpusher. This prevents moving stockpiled resources to workshop/granary and allows to sell their or use for building monuments. Cartpusher enabled by default

Remarks for code/texts are welcome. My English is bad, and this is my first C code.

### CODE REVIEW

**Comment by Legionary2** [comment]
Hello there , I am a little confused on some points. Are you saying the clay pit can internally store resources and not have to deliver to a warehouse when the option of stockpiling is enabled ?

**Comment by ipanic** [comment]
> Hello there , I am a little confused on some points. Are you saying the clay pit can internally store resources and not have to deliver to a warehouse when the option of stockpiling is enabled ?

No, it delivers resources to the nearest compatible warehouse instead of workshop

**Comment by MSTVD** [comment]
correct me if I am wrong, but this is how I see your proposal:

Instead of having to stockpile specific resources across all city via trade advisor, it'll let you stockpile specific resources via individual workshops

Am I correct?

**Comment by ipanic** [comment]
> correct me if I am wrong, but this is how I see your proposal:
> 
> Instead of having to stockpile specific resources across all city via trade advisor, it'll let you stockpile specific resources via individual workshops
> 
> Am I correct?

Yes, You are right

**Comment by MSTVD** [comment]
And in order for individual workshops to be able to stockpile, you need to have a designated warehouse that allows them to in the first place, right?

**Comment by ipanic** [comment]
> And in order for individual workshops to be able to stockpile, you need to have a designated warehouse that allows them to in the first place, right?

Of course

**Comment by Legionary2** [comment]
> > And in order for individual workshops to be able to stockpile, you need to have a designated warehouse that allows them to in the first place, right?
> 
> Of course

Would you like to come to the discord server for August’s and speak with our coders ? What is your interest level ?

**Comment by MSTVD** [comment]
If you want to join, drop your discord username and ID

**Comment by ipanic** [comment]
764052090867548170 / Andrey B#9832

**Comment by MSTVD** [comment]
Sent

**Pull request closed without merging**
