### PR TITLE
Improve launch icons for Android & Switch, change background image for PS Vita menu

### PR DESCRIPTION
**Pull request by Ouaz**
**- Android**

- Add a pink marble background (like in the game) and a soft shadow to the coin.
- Will only be used on Android 8.0 and above, as an adaptive icon, instead of the legacy icon being downscaled on a white background. Legacy icon (current augustus.png) will still be displayed on Android 7.0 and below.

icon_augustus_preview_66dp
(3 icon shapes as examples, but any shape will be supported)

**- Vita**

- Change the background image with a city from Augustus. Same land topography (coastline) so launch menu texts are above the water.
- PNG 8 bits, indexed colors

bg
startup

**- Switch**

- Improve the launch icon the same way than on Android.
- JPEG increases to 256x256 (like Julius Switch icon size)

icon0

### CODE REVIEW

**Comment by crudelios** [comment]
I really like your vita changes, but I'm torn about the marble background for the main icon.

Let me think about it, but meanwhile, to see if your can help me decide, why do you think it's better to have the background?

**Comment by Ouaz** [comment]
> Let me think about it, but meanwhile, to see if your can help me decide, why do you think it's better to have the background?

Currently, the android icon looks like this:

current_android_icon

This icon is a bit "rough" for a few reasons:

- Having a single object with no background is good when this object is a vector icon (like google icons for example, and many others). Here, we have real image from an ancient coin, with various details and color gradients, which doesn't merge well with a white background (it looks a bit "flat"), and various OEM icon shapes (circle, square, squircle, etc)

- So I followed these touch icon creation guidelines: https://material.io/design/iconography/product-icons.html#specs:

icon_shape

1 - The full icon
2 - The marble background
3 - The coin circle (caesar augustus name)
4 - Head of Augustus
5 - Soft shadow to blend with the background. (soft, because if the shadow is trimmed for whatever reason -but it shoudn't occur-, the cut won't be very noticeable)

So whatever is the icon shape depending the OEM, the marble background will replace the white background. Here's some examples with an icon tester for iOS (not android, but it's roughly the same): https://appsparky.com/icon-tester-pro-icon/?id=aYHeWf

**But I agree it needs to be tested first** (I'm unable to do this). It _should_ look good, but with android device various pixel densities, the result is not 100% guaranteed (as I decreased a bit the coin size, to add the "safe area" and the shadow).
_____________________________________________________
Same story for Switch icon:

switch_menu

It needs to be tested too.

_____________________________________________________
I didn't change Vita icon, because Vita game icons are circles anyway (and moreover animated). So it's good.

_____________________________________________________
Finally, I have made other icons (for try purposes), but I found the pink marble to be the most fitting one.
android_icon_preview

**Comment by crudelios** [comment]
Calling @bvschaik for Julius too

**Comment by catalin-duta** [comment]
My two cents for Android: if it *does* have a background, it will be treated as a square and definitely forced to follow the system settings. If that's a white circle, the marble only makes it stand out more.
Screenshot_20211129-210619654 (1)
Screenshot for reference.
Can't Augustus use the same logic as Julius? The coin would be more visible that way.

**Comment by crudelios** [comment]
For me both Julius and Augustus have a white background...

**Comment by Ouaz** [comment]
> My two cents for Android: if it _does_ have a background, it will be treated as a square and definitely forced to follow the system settings.

I thought there were size specifications and safe area to respect, so the OEM system just adds "a kind of mask layer" (or trim the default icon), to display the icon with the system specific shape.

i.e. all icons are squares by default, and Android OS adds the rounded egdes for example.

In your screenshot, I don't understand why the Nox icon has rounded edges inside the circle? The Nox icon should be by default a square.

So, with what you're saying, we can have this?
circle_icon

Haha, I'm lost now. :sweat_smile:

**Comment by catalin-duta** [comment]
All my icons (Android 10 here) fit into two categories:
- square icons that the system shows inside a white circle. *some* of these have rounded corners, some with visibly much rounder corners. From this I gather that the icon itself has the rounding (it is not applied by Android) because of the couple that are square-square.
- presumably underlying square icons that have the system mask (circle) applied, like the Julius one. I am assuming that the "original" is a square because around half of the logos in this category are actually square, so there might be some "allow Android to crop the edges into a square" setting.

**Comment by Ouaz** [comment]
> From this I gather that the icon itself has the rounding (it is not applied by Android) because of the couple that are square-square.

On the first sample, the "square-square" icons should scale because it's the default (legacy should I say) android icon shape (radius of the corners is 8.33% of the size of the icon).

On the second sample, I can't say. It's the same icon shape that on my Samsung tablet (android 8.1). I have tiny games on it (like Yiotro games) which I'm sure have a square icon (simple png file), and the rounding edges are yet applied (it's not displayed as a square into a squircle). And I haven't any settings to choose icon shapes (AFAIK)

> presumably underlying square icons that have the system mask (circle) applied, like the Julius one. I am assuming that the "original" is a square

It seems on the 3rd sample that the OS trims the transparency parts of Julius icon, and as the main object is almost a circle, it fits the icon shape. That's weird it doesn't do the same thing with Augustus icon though.

For Omio icon, it's perfect for each settings because it's an adaptive icon in XML (with or without image files): https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
It requires several layers as distinctive images files, and the icon itself is build through an XML file.

EDIT: I was typing that when you updated your last post. ^^

Well, it seems that on recent android devices, icons of this PR won't look good. Thanks for informations you provided.

**Comment by catalin-duta** [comment]
My takeaways, for options of getting the Augustus icon to be a circle, without the circle-boxing:
- adaptive icons (seems time-consuming)
- there seems to be an older (Android 7 or so) option for iconRound directly in the manifest
- compare against Julius logo; I'm guessing the Augustus coin (visually, less of a circle compared to the Julius coin) has some pixels outside the "safe" circle.

**Comment by Ouaz** [comment]
> My takeaways, for options of getting the Augustus icon to be a circle, without the circle-boxing:
>- adaptive icons (seems time-consuming)

Actually, I think it's the solution, to make legacy icons and adaptive icons.

Under Android 8.0, the "legacy" icons work (the behaviour I expected with this PR). On Android 8.0 and 8.1, the "legacy" icons can possibly work, but it now depends of the OEM. Above Android 8, only adaptive icons will work for each shape.

The iconRound attribute works starting from Android 7 (only for this shape).

I'm digging into it, and it's not _that_ bad. I'll see if I can create the new assets for the adaptive icons (directly in .svg). But XML stuff is out of reach for me. :yum:

**Comment by catalin-duta** [comment]
I found this quite detailed conversion from legacy icons to adaptive icons: https://thewissen.io/adaptive-icons-in-android/
Complete with folder structure, XML file contents and GitHub PR link.
Maybe it helps?

**Comment by crudelios** [comment]
Thanks to both of you for checking this out.

I think I have enough information now to be able to keep the icon round in every case.

If you guys want to have a go, please go ahead, otherwise I'll eventually do it.

**Comment by Ouaz** [comment]
> I found this quite detailed conversion from legacy icons to adaptive icons: https://thewissen.io/adaptive-icons-in-android/
>Complete with folder structure, XML file contents and GitHub PR link.
> Maybe it helps?

Yes, very interesting and clear. But like here,  I can only find examples using a single color as background
 `<background android:drawable="@color/ic_launcher_background"/>`

with the color defined in another XML file
```
<resources>
    <color name="ic_launcher_background">#ffffff</color>
</resources>
```

So we will end up with same problem. The coin (at least bigger than if it was a legacy icon) but still on a white background.

I finished the adaptive icon assets, but with an image as background, and a very soft shadow around the coin: 

- Five background assets at 108dp x 108dp each (mdpi to xxxhdpi = 108x108px to 432x432px) according this converter : https://pixplicity.com/dp-px-converter 
dp_size

- Five foreground assets at 108dpx108dp too, but fitting the safe area of the adaptive icon keygrid:
keygrid

Blue circle is the full icon shape (here the circle, as it is the smallest shape), grey lines inside the blue circle represents the safe area. As Augustus icon is a circle, it's easy to scale it. I wanted to create foreground assets with the coin scaled to the full icon shape, but it is not recommended in the guidelines (due to paralax and scale effects which can be applied to the icon)

https://developer.android.com/guide/practices/ui_guidelines/images/Single_Icon_Parallax_Demo_01_2x_ext.gif

So, it gives for xhdpi:

marble_icon_preview

Finally, following the link posted by catalin-duta, let's say we name adaptive assets respectively `augustus_launcher_background` and `augustus_launcher_foreground` in each` mipmap-***dpi` folder, the code for `ic_launcher.xml` in `mipmap-anydpi-v26` folder should be:

```
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/augustus_launcher_background"/>
    <foreground android:drawable="@mipmap/augustus_launcher_foreground"/>
</adaptive-icon>
```
I'm not sure about the stuff to declare in `AndroidManifest.xml`. There is already `android:icon="@mipmap/augustus"` for the legacy icons (with white background). No need to add something else?

Well, let me know what you think about all that, and if I update the PR or not.

**Comment by catalin-duta** [comment]
The concept of dp seems to not be a fixed 1:X with px because it depends on screen dpi.
Just taking the proportions of the keylines into account, 66dp (safe circle) / 108dp (adaptive icon) x 512px (example size) = 312px could be a good fit for the coin staying a circle within circle icons. Of course, depends on the dpi...
But that's just theory not taking the parallax into account. And I have no clue how to make icons move or sway, my adaptive icons don't seem to budge.

For the AndroidManifest.xml, just expanding from legacy icon support, I think:
- keep android:icon="@mipmap/augustus"
- add android:roundIcon="@mipmap/augustus_round"

In the mipmap-anydpi-v26 folder, the XML files would be called augustus.xml and augustus_round.xml.
Then in these XMLs, considering the Augustus coin the foreground:
- <background android:drawable="@mipmap/augustus_background"/>
 - <foreground android:drawable="@mipmap/augustus"/>
With a possibility here to use augustus_round for foreground if we want a full circle.

Finally, in the rest of the mipmap- folders, I think we need:
- augustus.png (base icon, legacy, adaptive foreground)
- augustus_background.png (adaptive background)
- maybe augustus_round.png (strictly circle, used for some legacy and adaptive foreground circle)

My fingers are itchy to do something about this myself, but unfortunately my laptop is out of commission.

**Comment by Ouaz** [comment]
> The concept of dp seems to not be a fixed 1:X with px because it depends on screen dpi.

Yes, one dp (density-independent pixel) is one pixel on a 160 DPI screen. And the conversion formula is ` px = dp * (dpi / 160)` (everything explained here: https://developer.android.com/training/multiscreen/screendensities)

> Just taking the proportions of the keylines into account, 66dp (safe circle) / 108dp (adaptive icon) x 512px (example size) = 312px could be a good fit for the coin staying a circle within circle icons. Of course, depends on the dpi...

Yes, totally agreed, the coin could be bigger. For xxxhdpi (~640dpi) @ 108dp, and a 66dp safe area:

```
108 x (640 / 160) = 432px (image size)
66 x (640 / 160) = 264px (centered safe area diameter)
```

But the keygrid icon circle diameter is 52 dp (208px). I follow what is said here (https://medium.com/google-design/designing-adaptive-icons-515af294c783)

_Adaptive icons are 108dp x 108dp in size but are masked to a maximum of 72dp x 72dp. Because of the minimum reach of the mask, you can consider a centered 66dp diameter circle as a safe zone, guaranteed not to be clipped. Keyline shapes are the foundation of the icon grid helping your icon’s visual proportions be consistent with other apps’ icons . The keyline shapes are: Circles: 52dp [...]_

So, do I respect the icon size consistency (coin diameter would be 52dp) or do I use the full safe area (coin diameter would be 66dp)?

As I didn't know, I tested the site mentioned in the tutorial (https://easyappicon.com/) and it creates the foreground files with a coin diameter of roughly 52dp, like me (slightly bigger, but their coins are blurry). Example with hdpi:

Me: ic_launcher_foreground_162_hdpi Easyappicon : ic_launcher_foreground

I _think_ the bigger the coin can be, the best it is, so I _should_ scale the coin to 66dp. What do you think?
_________________________________________
> And I have no clue how to make icons move or sway, my adaptive icons don't seem to budge.

It depends the OEM or maybe there's settings for it on your device? If you can, install this little app: https://github.com/nickbutcher/AdaptiveIconPlayground#readme (ask no permission, 6.73mo, no worry)

It finds all installed apps on your device **that have** an adaptive icon. It allows then to change shape, test paralax, etc. if your device don't support them (like mine). I installed it, and I was surprised to see that not so much apps have an adaptive icon.

By the way, I found deeply hidden in my tablet options (Android 8.1), two icon settings named "Icons without frame" and "Icons with frame".

"Icon without frame" is basically a pure legacy icon setting, meaning an icon is displayed in its png raw state. In this mode, all icons have their own shape (if the icon is, let's say a star, a star is displayed - not a star in a square, circle, or anything else). 

legacy_icon_setting
Julius & Augustus icons looks as expected. But the setting itself makes the desktop quite a mess, with each icon having its own shape. I understand now why Google wanted to normalized that with adaptive icon starting from Android 8 and above.

"Icons with frame" applies the OEM icon shape (here a squircle). Any icons that are not adaptive, are downscaled and displayed on a white background (well, not all, strangely).

adaptive_icon_setting

Yiotro games icons are not adaptive, and are rounded-edge squares in legacy mode:

legacy_rounded_edge_icon

But the OEM squircle shape is yet applied to them in adaptive mode:

adaptive_rounded_edge_icon

Okay. ヽ(。_°)ノ
_________________________________________
> For the AndroidManifest.xml, just expanding from legacy icon support, I think:
> add android:roundIcon="@mipmap/augustus_round"

I'm not sure about android:roundIcon. It's actually only supported by Android 7.0, and **only** if the device applies round masks (i.e. the OEM icon shape is a circle). For Android 8.0 and above, adaptive icons do the job, `roundIcon` become useless.

"_For those of you with an android:roundIcon, you must keep that attribute to continue to support API 25 devices. Devices with round masks will use your custom roundIcon if available, but it is strongly suggested to use a single adaptive icon for those devices as well (this ensures you get the standard shadow, support for visual effects, etc)._"
https://medium.com/androiddevelopers/vectordrawable-adaptive-icons-3fed3d3205b5

"_Android 7.1 introduced roundIcon as an attempt to bring some consistency here but this was pretty restrictive to OEMs looking to differentiate their devices (i.e. only supporting circular icons) and lacked any kind of validation (developers could supply any shaped icon and pinky-swear that it was round!)._"
https://medium.com/google-design/understanding-android-adaptive-icons-cee8a9de93e2

"_You can ignore Round icons as they were only introduced in Android 7, but Legacy icons were still displayed properly in that Android version. However since Android 8 Adaptive icons have to be provided when the app targets api level 26 or higher. So you should provide Adaptive and Legacy icons. Adaptive icons will be displayed on devices with Android 8 and newer Android versions. Legacy icons will be displayed on devices with Android 7 and older Android versions.
If you only provide legacy icon, it will not be displayed properly on devices with Android 8 and newer versions._"
https://forum.unity.com/threads/do-i-need-to-make-adaptive-round-and-legacy-icons.547459/

So I don't use it, and stick to legacy and adaptive icons.

__________________________________________________________
```
Finally, in the rest of the mipmap- folders, I think we need:

    augustus.png (base icon, basically same as now, used for legacy and adaptive foreground)
    augustus_background.png (adaptive background)
    maybe augustus_round.png (strictly circle, used for some legacy and adaptive foreground circle)
```

Yes, we keep `augustus.png` as base icon for pre-android 8.0 devices (or if the device provides a "legacy icon setting"), but it can't be used as foreground for the adaptive icon. The two layers (background and foreground) must have a size of 108dp x 108dp (actual _augustus.png_ is 48dp x 48dp)

________________________________

To summary:

- create `augustus.xml` in `mipmap-anydpi-26` folder:

```
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/augustus_background"/>
    <foreground android:drawable="@mipmap/augustus_foreground"/>
</adaptive-icon>
```

- In each existing `mipmap-***dpi` folder, add `augustus_background.png` and `augustus_foreground.png`, with corresponding dpi size obviously.

- Finally in `AndroidManifest.xml`, nothing change I think. `android:icon="@mipmap/augustus"` is already used to declare the legacy icon, and if the device is android 8.0 or above, it will use `augustus.xml` instead by default (and therefore the adaptive icon).

"_Let’s assume your Android Manifest’s application tag has android:icon="@mipmap/ic_launcher". To add an adaptive icon that replaces those PNGs on API 26+ devices, you’ll add a res/mipmap-anydpi-v26/ic_launcher.xml file that looks like this [...]
By placing it in the mipmap-anydpi-v26 folder, the resource system will use it in preference over any files in the other dpi folders (exactly what you want, since this file is replacing all of them) and that it should only be used in API 26+ devices._"
https://medium.com/androiddevelopers/vectordrawable-adaptive-icons-3fed3d3205b5

**Comment by catalin-duta** [comment]
I think that through a combination of OEM/Android, some legacy icons don't go through the whole process of downscaling and squircle-boxing. Like Julius in my case and the Yiotro games in yours.
My working theory:
- take the legacy icon PNG
- apply the system mask
- if there is any transparency in the visible area (after mask is applied), then downscaling + background color is applied.
Seems to work for the Yiotro games (no transparency) and Augustus (see the gap on the right edge compared with the keyline circle).

Anyway, for the adaptive icon we could try with 66dp.
The 52dp I think is a good fit for the elements of more abstract logos, which also need a background. These would look rather strange if they were hugging the edge of the 66dp circle:
Screenshot_20211202-121513347 (1)

I can imagine that the CAESAR AVGVSTVS part might be out-of-frame for special effects (parallax etc.) but to me that is more of a fine detail than a logo element.

**Comment by Ouaz** [comment]
I increased the coin to 66dp, and tried to center it as much as possible, as the coin shape is irregular.

keygrid_xxxhdpi_66dp

It should finally give that: 

icon_augustus_preview_66dp

I also updated the Switch icon.
icon0

The PR is ready for review.

**Comment by crudelios** [comment]
Yeah, update the icon size please 🙂

**Comment by Ouaz** [comment]
Switch icon updated. But it seems the Android build failed again (well, it is a success, but no artifacts created). Is this normal?

So, no test yet to know if the adaptive icon works or not. Haha.

**Comment by crudelios** [comment]
> it seems the Android build failed again (well, it is a success, but no artifacts created)

Android doesn't create artifacts for PR's. It was @bvschaik's decision back then for Julius, and we haven't really changed it for Augustus.

@Keriew @Legionary2 what do you think of these? Good to merge?

**Comment by Keriew** [comment]
I think they look great!

**Comment by Ouaz** [comment]
Looks good with all shapes on [AdaptiveIconPlayground](https://github.com/nickbutcher/AdaptiveIconPlayground#readme), and the paralax and scaling work as expected.

Big thanks @catalin-duta for your help, it was really useful and your posts helped me a lot (great advise to push the coin size to 66dp, it would have look to small otherwise).

**Comment by Ouaz** [comment]
crack_too_strong

Mmmmh, on my tablet screen, the crack and shadow on the lower right are bit visually disturbing, especially with the circle shape icon, as the crack is right on the edge. I should have attenuate it more, like on the left.

Do you have the same impression, or is it just me (and my screen)?

Mr. Nitpicky

**Comment by crudelios** [comment]
I guess? Once seen, cannot be "unseen" 😉 

Go ahead and change it if you wish!

**Comment by catalin-duta** [comment]
I can't see it on my screen, as the icon barely takes up 9mm (395 ppi screen), but I guess it could be a bit distracting if you look close.

**Comment by Ouaz** [comment]
> Once seen, cannot be "unseen"

So true. But finally, I get used to it. And above all, "_If it ain't broke, don't fix it_" (works well against OCD syndrom :rofl: )

> I can't see it on my screen, as the icon barely takes up 9mm (395 ppi screen), but I guess it could be a bit distracting if you look close.

Yep, my screen is ~224 dpi (1200x1920, 10.1"), that's maybe why.

By the way, do you play Julius/Augustus with a stylus or fingers? 

On my tablet, the .ini file says that the screen resolution is 1440x900 (?) (landscape mode) and downscaled to 1261x863 (Julius) Anyway, even with this downscaling, I found the UI to be still too small (especially buildings buttons in the sidepanel, a lot of misclicks or "mistouchs" should I say) and it's hard to click-drag efficiently on the map (the cursor touch zone is too small). Not game breaking, but annoying enough sometimes, as it's not possible to set scale like on PC.

What's your experience on your very high dpi screen?

**Comment by catalin-duta** [comment]
I play with my fingers, but luckily I have rather slim fingers and the touch detection on my phone does a pretty good job even if I tap with the side of my fingers. Like when I'm using the on-screen keyboard for typing, I have very few misses compared to my previous phones.
This is the resolution I find in the .ini file:
`Window resized to 2400 x 1080 INFO: Maximum scale of 225 applied`

I would be tempted to use a stylus like PDAs used to have, like a thin stick. The pen-like ones (like for drawing tablets) rather cover the screen because of their thickness and the pencil-like ones with rubber on the end are way more imprecise than my fingers. But I haven't seen such a stylus sold anywhere, and I would also be scared of losing such a small thing because my phone doesn't have a pocket for it.

The side panel is ok to me, just the occasional miss when selecting a building inside a menu when I end up building a different temple than intended.
I find click-drag good: I've seen worse and this is a game not designed for touchscreens anyway. But I tend to stay inside the visible area of the city, because if I'm not *very* precise I will end up dragging the e.g. gardens to build across half of the city map.

Placing single buildings is good, because I can adjust the position, except for reservoirs. I go through a lot of clicks to place a single reservoir, because I don't normally place them in the reservoir-aqueducts-reservoir pattern. Most of the time I don't get the placement right on the first several clicks and it doesn't let me really adjust, because it's already trying to place the second reservoir. It makes things a bit cumbersome when expanding a water network inland, plus I like to control where the aqueducts go.

I've had instances when some part of the screen doesn't let me click on it, like I can't use the menu or side panel, where I need to click on a building, bring up its screen and close it. But that happens when I have at least 2 fingers moving around the screen, so I take it that I must have clicked in two places at once and it gets confused.

Finally, the File menu is a bit tricky to reach because it's at the very edge of the screen and I can only see *ile* because of (surprise!) rounded screen corners. That's on landscape, on portrait the only whole letter is *e*. But I got used to it rather quickly, it doesn't take me more than 5 tries anymore :D

**Comment by Ouaz** [comment]
Thanks for this detailed answer. We have globally the same experience then.

> The side panel is ok to me, just the occasional miss when selecting a building inside a menu when I end up building a different temple than intended.

Same here. 

> Placing single buildings is good, because I can adjust the position, except for reservoirs. I go through a lot of clicks to place a single reservoir, because I don't normally place them in the reservoir-aqueducts-reservoir pattern. Most of the time I don't get the placement right on the first several clicks and it doesn't let me really adjust, because it's already trying to place the second reservoir. It makes things a bit cumbersome when expanding a water network inland, plus I like to control where the aqueducts go.

Yes, it can be annoying (as the game thinks it's a drag-click to build a second reservoir) but I use a tip to place and build a reservoir in 3 clicks, with a consistent result:

1) Place your reservoir above water. A red square appears.
2) Do not lift your finger and drag the red square on the land. It will change to the usual reservoir ghost image, empty or full of water depending the location, like on PC. Drag as much as you want without lifting your finger, until you find the adequate location.
3) Then lift your finger, and click exactly on this part of the reservoir (light touch): 

reservoir

4) The full reservoir changes to a red square again. Click on the red square exactly on the same spot like in point 3 (still with a light touch)
5) The full reservoir reappears. Click a last time the reservoir on the same spot. It will be finally built.

This 3-clicks building process works 90% of the time. Even when you want to build a reservoir in the far inland, just place first your reservoir above a water plan, and repeat the process. :point_up: 

> Finally, the File menu is a bit tricky to reach because it's at the very edge of the screen and I can only see ile because of (surprise!) rounded screen corners. That's on landscape, on portrait the only whole letter is e. But I got used to it rather quickly, it doesn't take me more than 5 tries anymore :D

Haha, so true.

**Comment by catalin-duta** [comment]
I'll give it a try with the 3-clicks, thanks for the tip @Ouaz !
It might be tricky if building inland in a rather buildable area (where it doesn't turn red). I get the point of putting it first on water (or maybe a mountain), but the water might be outside the screen and then I might end up dragging it somewhere else entirely (per above).


To be fair, @crudelios , the draggable reservoir thing is pretty neat. I wouldn't say remove it, because on higher-res tablets or maybe touch laptops it might be very workable and useful. 
Just maybe, as future enhancement, after placing one reservoir (inland), while dragging the second reservoir + aqueducts, it lets you "place" the second reservoir on top of an existing one, so just creating the aqueduct connection.

**Pull request merged**
