### PR TITLE
Add city health rating value to health advisor

### PR DESCRIPTION
**Pull request by Ouaz**
- Also add "Disease surveillance" subtitle to make clearer that city_health (which is global) and sickness_level (which fetches the house with the higher sickness value in the city) are somewhat independent under some circumstances.
- Thanks to Awatibala/dvincent56 for the proofreading.

image

### CODE REVIEW

**Comment by crudelios** [comment]
I think it would be better/ more visible if the "Rating: 96" was between the title "City health" and the first paragraph ("City health is almost perfect, ..."). As it stands it's pretty easy to miss, and it's an important value to display.

I'm sure it can be done by moving everything else a little bit downward

**Comment by Ouaz** [comment]
rating

**Comment by crudelios** [comment]
Nitpick: can you vertically center the "Rating: 96" between the title and the first paragraph please?

**Comment by Ouaz** [comment]
2 pixels up:

image

**Comment by crudelios** [comment]
Perfect!

**Comment by Ouaz** [comment]
Ah yes, this is ready to merge (sorry, I force-pushed the centering commit) ^^

**Comment by crudelios** [comment]
Done 🙂

**Pull request merged**
