### PR TITLE
Change market access calculation to granaries/warehouses and display in UI.

### PR DESCRIPTION
**Pull request by PrettyFlower**
It just occurred to me that this might confuse people with "houses covered by the market". Might need to change it to something like highlighting the granaries/warehouses that are in range.

### CODE REVIEW

**Comment by Ouaz** [comment]
> It just occurred to me that this might confuse people with "houses covered by the market".

Yeah, I thought it was that at first. ^^ 

> Might need to change it to something like highlighting the granaries/warehouses that are in range.

Maybe (not sure of the wording):

"Show granary/warehouse access range when building markets"

?

**Comment by PrettyFlower** [comment]
The original calculation was from the market's road access point to the top tile of the granary. I think that was fine when it was hidden from the user, but it's pretty unintuitive to actually show that to someone. Rather than try and come up with a way to display that, I changed the calculation to just be the tiles between the edges of the granary/warehouse and market. It's a little bit more complicated to calculate on the simulation side, but a lot easier to show visually and understand as a user.

**Comment by crudelios** [comment]
Ok then change the title of the PR to "change the way the distance from markets is calculated and convey it in the UI" or something.

Also, I think this one should stay for after v3.2.0 release, it will do well with the theme of the v4.0 release.

**Comment by crudelios** [comment]
Pinging @PrettyFlower. Do you still want this merged?

**Comment by PrettyFlower** [comment]
Yeah I think this would still be a good one to have. We had talked about changing around the pathing logic for market suppliers so they would pick granaries based on the road distance rather than the straight line distance, but I'm not sure I'll ever get there so I'd rather merge it "as is".

**Pull request merged**
