### PR TITLE
Add waypoints as an extra configuration for preview

### PR DESCRIPTION
**Pull request by AlanBF1992**
Waypoints can be added to the roamer preview for single buildings, when clicking or building them.

### CODE REVIEW

**Comment by crudelios** [comment]
Sorry for the long delay, I've been busy!


I'm not really sure about this one. To me, after the walker preview, adding the waypoints back doesn't make much sense.

Still, I'd like input on guys like @Keriew, @PrettyFlower and @UberWaffe.

**Comment by PrettyFlower** [comment]
@Keriew I missed the discussion on these, do you know where I can find it? My gut feeling is to leave them out just because I prefer to keep features as lean as possible (I've dealt with sooo many bugs in various codebases due to features not working together properly) but I'd like to see the counter points in favor of the waypoints.

**Comment by UberWaffe** [comment]
> 

It was on the Zakhcolytes discord on the augustus-development channel.
https://discord.com/channels/136544899339124736/729015268449452103/1083007753590681611

**Comment by crudelios** [comment]
I believe we all agree for now that this should not be merged.

@AlanBF1992 Though we appreciate your efforts, as you can see, for now we don't think this should be added to Augustus, even as an option. Therefore I'm closing the PR.

However, you can keep using them yourself as they don't really affect the gameplay so you'll have no incompatibility issues.

**Pull request closed without merging**
