### PR TITLE
Add "no disease" tooltip on sickness overlay

### PR DESCRIPTION
**Pull request by Ouaz**
Show "No disease" tooltip when hovering over a house with no sickness column on sickness overlay.

### CODE REVIEW

**Comment by Ouaz** [comment]
Oh, the value is 1 not 5. I thought cartpusher triggered + 5 by default, making the smallest bit of column appears.

**Comment by crudelios** [comment]
Also, can you make it so that a building that can't have disease doesn't show any tooltip at all?

**Comment by Ouaz** [comment]
Ah, you're right, but I have to ask Awatibala about this. ^^

**Comment by Ouaz** [comment]
Well, he is very busy, I don't want to disturb him. :p

I'm a total newbie in coding, so don't laugh if this below is totally wrong. ^^ But is it possible?

```
{
    if (building_is_house(type) || b->type == BUILDING_DOCK || b->type == BUILDING_WAREHOUSE || b->type == BUILDING_GRANARY) {
        if (b->sickness_level < 1) {
            c->translation_key = TR_TOOLTIP_OVERLAY_SICKNESS_NONE;
        } else if (b->sickness_level < LOW_SICKNESS_LEVEL) {
            c->translation_key = TR_TOOLTIP_OVERLAY_SICKNESS_LOW;
        } else if (b->sickness_level < MEDIUM_SICKNESS_LEVEL) {
            c->translation_key = TR_TOOLTIP_OVERLAY_SICKNESS_MEDIUM;
        } else if (b->sickness_level < HIGH_SICKNESS_LEVEL) {
            c->translation_key = TR_TOOLTIP_OVERLAY_SICKNESS_HIGH;
        } else {
            c->translation_key = TR_TOOLTIP_OVERLAY_SICKNESS_PLAGUE;
        }
        return 0;
    }
}
```

**Comment by crudelios** [comment]
Almost correct. 

The `return 0;` should be outside the `if`, at the end.

Other than that, that's exactly it!

**Pull request merged**
