### PR TITLE
Load assets from custom dir

### LINKED ISSUE #188: Where should the mods directory be installed for augustus to find it?
As it currently stands I was only able to get the additional mods to work by cloning the repository and copying the contents of the `mods` dir to `.cache/julius/app/mods/`.

Is there any way to install this at the system-wide level (perhaps in `/usr/share/augustus`, as seems reasonable per the FHS) so that augustus can automatically find them? This has two rationales:

1. These files seem to not require modification by the user, and therefore it would make sense for them to be available to all users and not require write access.
2. The Gentoo Linux distribution (for which I am currently trying to package it), prefers to not install files into the user's home, as this should be left to the application or the user.

### PR DESCRIPTION
**Pull request by crudelios**
Allows loading assets from many different directories instead of just the base directory

This allows building the assets in Vita, Switch, mac OS and Android and also allows using the proper FOSS folders on Linux.

Note that you can't mix and match different directories. The game searches for a valid directory in a specific order, and if the folder exists it will be used to load mods, even if the folder is empty.

The first folder to be searched is always the folder where the C3 install is. Windows won't look anywhere else, mac will look inside the app bundle, Linux will search all these directories (in this order):

```
    "../share/augustus-game"
    "~/.local/share/augustus-game"
    "/usr/share/augustus-game"
    "/usr/local/share/augustus-game"
    "/opt/augustus-game"
```

Every version also supports the directory specified by `${CMAKE_INSTALL_DATADIR}`.

Another very big change is that I replaced every mention of `mod` with `asset`. Accordingly, the main tag of the XML files is no longer `mod`, but the more appropriate `assetlist`. @Areldir This is particularly relevant to you.

This will fix #188 and #172 and finally pave the way for Switch, Vita and Android support (in fact this PR already builds and runs on them all).

### CODE REVIEW

**Comment by Riww** [comment]
Pretty sure this has broken finding assets directory on windows. Latest builds say there is no 'assets' folder despite there is.

**Comment by crudelios** [comment]
This is not broken. The xml files for assets have changed so you need to get the new assets folder from github for it to work. Simply renaming `mods` to `assets` won't do.

**Comment by Riww** [comment]
You are right, still the error message is wrong. It shall say that the xml files in the assets folder are wrong/outdated, not that the assets folder can't be found.

**Comment by crudelios** [comment]
You're right, I'll change the error message to be more descriptive.

**Pull request merged**
