### PR TITLE
Build menu shows resources needed for construction

### PR DESCRIPTION
**Pull request by nishantjr**
One issue is the icons for marble/lumber/clay are too big for the labels.

### CODE REVIEW

**Comment by Keriew** [comment]
Hey, thank you for the PR! I like the idea of showing the total resource cost before construction, but I don't think it looks too good visually.

Maybe the information could be moved to a tooltip? This way it'd have more space, without crowding the already big and busy construction button.

**Comment by nishantjr** [comment]
@Keriew I agree. Where's a good example re how to set up tooltips?

**Comment by Keriew** [comment]
Tooltips are handled in their relevant window structure, so you'll need to define a tooltip function for window structure in `window\build_menu.c`. You can check any window structure for how it's usually done, like `window\advisors.c`. I don't think

**Comment by nishantjr** [comment]
OK, my ideal solution would be if we had smaller resource icons, but I guess that that  a lot more work.

**Comment by crudelios** [comment]
I ended up adding this as a tooltip.

Thank you for the idea!

**Pull request closed without merging**
