### PR TITLE
New hotkey for Risks/Native overlay

### PR DESCRIPTION
**Pull request by BazzaCuda**
New hotkey for Risks/Native overlay

### CODE REVIEW

**Comment by Ouaz** [comment]
121 commits... what's happening? 😅

**Comment by BazzaCuda** [comment]
> 121 commits... what's happening? 😅

I know! I don't understand it. Github says my fork is 121 commits *ahead* of your repository.
But apart from my pull requests (three now, I think?), all I ever do is "Sync Fork", to get the latest commits from your repository to my fork.

I don't know why it thinks I'm *any* commits ahead. Unless I'm misunderstanding what "Sync Fork" does (?)

**Comment by crudelios** [comment]
If you sync the fork when you have changes of your own, git will create a merge commit.

In order to avoid such a commit, you can either rebase instead of merging - beware, only do this if you haven't published the branch - or stash your changes, sync with master (when there are no differences you won't get a merge commit but your local fork will be updated anyway) and pop the stash.

Simple? No, but this is git, it's as powerful as it is incomprehensible.

**Comment by BazzaCuda** [comment]
Ah, ok, thanks. Maybe my fork isn't entirely clean like I think it is.
I think I might scrap my fork and re-fork it. I assume that Github will forget anything about the original fork (?)

Assuming my pull request is good, I should wait until that has been merged into Keriew-master first, yes, or I'll have to re-do the whole thing ?

Apart from looking odd at your end, do those 121 commits actually cause problems at your end?

**Comment by crudelios** [comment]
You don't need to delete the entire fork, it's just the branch that is dirty.

Anyway, there are no issues here, git has detected those are merge commits that are already part of master and when merging the PR all those commits will be squashed together.

**Pull request merged**
